name: mi_reclamo
description: "App para realizar reclamos"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.4.0
  dio: ^5.6.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  uuid: ^4.5.1
  http: ^1.2.2
  material_symbols_icons: ^4.2785.1
  google_fonts: ^6.2.1
  file_picker: ^8.1.4
  flutter_svg: ^2.0.16
  skeletonizer: ^1.4.2
  intl: ^0.20.1
  flutter_staggered_animations: ^1.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo-app-small.png
    - assets/logo-app.svg
    - assets/large-logo-app.svg